dev:
  server:
    port: 8001
    opts:
      cors:
        headers: ['authorization', 'Content-Type']
  mongo:
    uri: mongodb://localhost/ride-better-dev
  catbox:
    mongo :
      partition : "ride-better-dev-cache"
  auth:
    user : "baio"
  msw:
    key: "ni5E1bOpV0KM3Hl31ZBkkQ6jAXXEaJHL"
  elasticsearch:
    host : "localhost:9200"
debug:
  server:
    port: 8001
    opts:
      cors:
        headers: ['authorization', 'Content-Type']
  mongo:
    uri: mongodb://localhost/ride-better-dev
  catbox:
    mongo :
      partition : "ride-better-dev-cache"
  msw:
    key: "ni5E1bOpV0KM3Hl31ZBkkQ6jAXXEaJHL"
  elasticsearch:
    host : "localhost:9200"
  secret : "allBestthings1979"
test:
  server:
    port: 8002
  mongo:
    uri: mongodb://localhost/ride-better-dev
  elasticsearch:
    host : "localhost:9200"
    log : "trace"
  catbox:
    mongo :
      partition : "ride-better-dev-cache"
  secret : "allBestthings1979"
stage:
  server:
    opts:
      cors:
        headers: ['authorization', 'Content-Type']
  catbox:
    mongo :
      host : ds053080.mongolab.com
      port : 53080
      username : baio
      password : 123
      partition : heroku_app31445045
  msw:
    key: "ni5E1bOpV0KM3Hl31ZBkkQ6jAXXEaJHL"
  secret : "allBestthings1979"
