dev:
  server:
    port: 8001
    opts:
      cors:
        headers: ['authorization', 'Content-Type']
  mongo:
    uri: mongodb://localhost/ride-better-dev
  catbox:
    mongo :
      partition : "ride-better-dev-cache"
  auth:
    user : "baio"
  forecastio:
    key: c627c992deb04400940b50c6e1ee0562
  elasticsearch:
    host : "localhost:9200"
debug:
  server:
    port: 8001
    opts:
      cors:
        headers: ['authorization', 'Content-Type']
  mongo:
    uri: mongodb://localhost/ride-better-dev
  catbox:
    mongo :
      partition : "ride-better-dev-cache"
  forecastio:
    key: c627c992deb04400940b50c6e1ee0562
  elasticsearch:
    host : "localhost:9200"
  secret : "allBestthings1979"
test:
  server:
    port: 8002
  mongo:
    uri: mongodb://localhost/ride-better-dev
  elasticsearch:
    host : "localhost:9200"
    log : "trace"
  catbox:
    mongo :
      partition : "ride-better-dev-cache"
  secret : "allBestthings1979"
  forecastio:
    key: c627c992deb04400940b50c6e1ee0562
stage:
  server:
    opts:
      cors:
        headers: ['authorization', 'Content-Type']
  catbox:
    mongo :
      host : ds053080.mongolab.com
      port : 53080
      username : baio
      password : 123
      partition : heroku_app31445045
  forecastio:
    key: c627c992deb04400940b50c6e1ee0562
  secret : "allBestthings1979"
