"use strict"

module.exports = [
  require("./spots-find")
  require("./home-get")
  require("./reports-post")
  require("./nearest-spot-get")
  require("./webcams/webcams-latest-get")
  require("./webcams/webcams-latest-noindex-get")
  require("./webcams/webcams-next-get")
  require("./webcams/webcams-prev-get")
  require("./resorts/resorts-info-get")
  require("./resorts/resorts-maps-get")
  require("./resorts/resorts-prices-get")
  require("./resorts/resorts-info-main-put")
  require("./resorts/resorts-info-header-post")
  require("./resorts/resorts-contacts-put")
  require("./resorts/resorts-proscons-put")
  require("./resorts/resorts-maps-put")
  require("./resorts/resorts-prices-put")
  require("./resorts/resorts-price-post")
  require("./resorts/resorts-webcams-put")
  require("./resorts/resorts-post")
  require("./resorts/resorts-spot-get")
  require("./threads/thread-get")
  require("./threads/threads-get")
  require("./threads/replies-delete")
  require("./threads/replies-post")
  require("./threads/replies-put")
  require("./threads/threads-delete")
  require("./threads/threads-post")
  require("./threads/threads-img-post")
  require("./threads/threads-put")  
  require("./threads/threads-img-put")  
]