"use strict"

module.exports = [
  require("./spots/spots-find")
  require("./home-get")
  require("./reports-post")
  require("./spots/nearest-spots-get")
  require("./webcams/webcams-latest-get")
  require("./webcams/webcams-latest-noindex-get")
  require("./webcams/webcams-next-get")
  require("./webcams/webcams-prev-get")
  require("./resorts/resorts-info-get")
  require("./resorts/resorts-maps-get")
  require("./resorts/resorts-prices-get")
  require("./resorts/resorts-info-main-put")
  require("./resorts/resorts-contacts-put")
  require("./resorts/resorts-proscons-put")
  require("./resorts/resorts-maps-put")
  require("./resorts/resorts-prices-put")
  require("./resorts/resorts-price-post")
  require("./resorts/resorts-webcams-put")
  require("./resorts/resorts-post")
  require("./resorts/resorts-spot-get")
  require("./board/thread-get")
  require("./board/threads-get")
  require("./board/replies-delete")
  require("./board/replies-post")
  require("./board/replies-put")
  require("./board/threads-delete")
  require("./board/threads-post")
  require("./board/threads-img-post")
  require("./board/threads-put")  
  require("./board/threads-img-put")  
  require("./board/transfers/transfer-request-post")  
  require("./board/transfers/transfer-request-delete")  
  require("./board/transfers/transfer-accept-request-put")  
  require("./history/snowfall-history")  
]