id: "web-api-controller"
kind: "ReplicationController"
apiVersion: "v1beta1"
desiredState: 
  replicas: 3
  replicaSelector: 
    name: "web-api"
  podTemplate: 
    desiredState: 
      manifest: 
        version: "v1beta1"
        id: "web-api-controller"
        containers: 
          - 
            name: "web-api"
            image: "baio/ride-better-web-api"
            cpu: 1000
            ports: 
              - 
                name: "web-api-port"
                containerPort: 8001
                hostPort: 85
            env:
              - name: "NODE_ENV"
                value: "gce-stage"
              - name: "MONGO_URI"
                value: "mongodb://10.240.108.4/ride-better-stage"
              - name: "REDUCED_MONGO_URI"
                value: "mongodb://10.240.108.4/ride-better-stage"
              - name: "WEBCAMS_MONGO_URI"
                value: "mongodb://10.240.108.4/ride-better-stage"
              - name: "ELASTIC_URI"
                value: "10.240.204.157:9200"
              - name: "PORT"
                value: "8001"
              - name: "FORECASTIO_KEY"
                value: "c627c992deb04400940b50c6e1ee0562"                
    labels: 
      name: "web-api"
labels: 
  name: "web-api"